// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVjdbbDiYpzri15eOPN7E7Cmhqf6RJn40',
    appId: '1:461342906551:web:782340d3c544fb34635532',
    messagingSenderId: '461342906551',
    projectId: 'loglife-e0ad5',
    authDomain: 'loglife-e0ad5.firebaseapp.com',
    storageBucket: 'loglife-e0ad5.firebasestorage.app',
    measurementId: 'G-6BWLX842QF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOqJHOviHpJIF36leBaOE2Vl_GS0xryMw',
    appId: '1:461342906551:android:ce575ae527771b22635532',
    messagingSenderId: '461342906551',
    projectId: 'loglife-e0ad5',
    storageBucket: 'loglife-e0ad5.firebasestorage.app',
  );

}